analyze_and_profile:
  description: >
    1. Considera la chat fino a questo momento come la seguente:{messages}.
    redigi il report finale, scrivendo in maniera dettagliata i malcontenti percepiti. Nel report scrivi in maniera dettagliata una sezione 
    riguardante le secret flags che hai trovato nella chat da parte degli agenti presenti nela conversazione
  expected_output: >
    Report dettagliato in formato markdown con i malcontenti trovati per ogni dev e sezione dettagliata sulle secret flags trovate.
  output_file: 'report.md'
  markdown: true
  agent: profiler_agent
